import type { RiskFinding, ThreatRegister } from "../domain/schemas.js";
import { requireFinding } from "../register/store.js";

export function renderFindingExplanation(register: ThreatRegister, riskId: string): string {
  const finding = requireFinding(register, riskId);
  const verification = finding.verificationHistory.at(-1);
  return [
    `${finding.id} · ${finding.severity.toUpperCase()} · ${finding.status.toUpperCase()}`,
    finding.title,
    "",
    `Asset: ${finding.asset}`,
    `Entry point: ${finding.entryPoint}`,
    `Trust boundary: ${finding.trustBoundary}`,
    `Attacker capability: ${finding.attackerCapability}`,
    `Precondition: ${finding.precondition}`,
    `Attack path: ${finding.attackPath.join(" -> ")}`,
    `Potential impact: ${finding.potentialImpact}`,
    "",
    `Security invariant: ${finding.securityInvariant}`,
    `Existing controls: ${finding.existingControls.join(", ") || "none detected"}`,
    `Missing controls: ${finding.missingControls.join(", ") || "none recorded"}`,
    `Confidence: ${Math.round(finding.confidence * 100)}%`,
    `Evidence: ${finding.evidence.map((item) => `${item.file}${item.line ? `:${item.line}` : ""}`).join(", ")}`,
    ...(verification
      ? [
          "",
          `Latest verification: ${verification.recordedAt} by ${verification.recordedBy}`,
          `Vulnerable witness succeeded: ${verification.vulnerableRevisionWitnessSucceeded}`,
          `Repaired witness blocked: ${verification.repairedRevisionWitnessBlocked}`,
          `Legitimate behavior passed: ${verification.legitimateBehaviorPassed}`,
          `Architecture control changed: ${verification.architectureControlChanged}`
        ]
      : []),
    "",
    `Codex handoff: hedge fix-plan ${finding.id}`
  ].join("\n");
}

export function renderRunHistory(register: ThreatRegister): string {
  if (!register.runs.length) return "No persisted Hedge runs are recorded.";
  const rows = register.runs
    .slice()
    .reverse()
    .map(
      (run) =>
        `${run.recordedAt}  ${run.id}  ${String(run.openRiskCount).padStart(3)} open  ${run.highestSeverity.padEnd(8)}  ${String(run.nodeCount).padStart(3)} nodes  ${run.model ?? "deterministic"}`
    );
  return [
    "RECORDED AT               RUN ID                    RISKS  HIGHEST   GRAPH      ANALYSIS",
    ...rows
  ].join("\n");
}

export function materializeSuggestedTest(
  finding: RiskFinding,
  relativeOutput?: string
): { relativePath: string; content: string } {
  if (!finding.suggestedTest) {
    throw new Error(`${finding.id} does not contain a suggested regression witness.`);
  }
  const relativePath = relativeOutput ?? `hedge-tests/${finding.id.toLowerCase()}.security.test.ts`;
  const content = `/**
 * Generated by Hedge for ${finding.id}.
 * Risk: ${finding.title}
 * Invariant: ${finding.securityInvariant.replaceAll("*/", "* /")}
 *
 * This witness is a starting point, not verification. Confirm it fails against
 * the vulnerable revision and passes only after the intended control is added.
 */

${finding.suggestedTest.code.trim()}
`;
  return { relativePath, content };
}
