/**
 * Generated by Hedge for HEDGE-001.
 * Risk: New mutating entry point has no detected authentication control
 * Invariant: Only authenticated and authorized principals may invoke POST /api/files/upload.
 *
 * This witness is a starting point, not verification. Confirm it fails against
 * the vulnerable revision and passes only after the intended control is added.
 */

it("rejects unauthenticated access to POST /api/files/upload", async () => {
  const response = await requestWithoutSession();
  expect([401, 403]).toContain(response.status);
});
