import { describe, expect, it } from "vitest";
import { analyzeWithHeuristics } from "../../src/analysis/heuristics.js";
import type { GraphDelta } from "../../src/domain/schemas.js";
import { emptyRegister, mergeFindings } from "../../src/register/store.js";
import {
  materializeSuggestedTest,
  renderFindingExplanation,
  renderRunHistory
} from "../../src/report/finding.js";

const delta: GraphDelta = {
  addedNodes: [
    {
      id: "entrypoint:delete",
      kind: "entrypoint",
      label: "DELETE /api/users/:id",
      trustZone: "public",
      evidence: [{ file: "route.ts", line: 4, extractor: "test" }],
      controls: [],
      metadata: { method: "DELETE", dynamicResource: true }
    }
  ],
  removedNodes: [],
  changedNodes: [],
  addedEdges: [],
  removedEdges: [],
  changedEdges: []
};

describe("finding output", () => {
  it("renders a focused explanation and a materialized witness", () => {
    const register = emptyRegister();
    const { runFindings } = mergeFindings(register, analyzeWithHeuristics(delta));
    const finding = runFindings[0]!;
    expect(renderFindingExplanation(register, finding.id)).toContain("Security invariant:");
    const witness = materializeSuggestedTest(finding);
    expect(witness.relativePath).toContain(finding.id.toLowerCase());
    expect(witness.content).toContain(`Generated by Hedge for ${finding.id}`);
  });

  it("renders persisted history without exposing raw graph data", () => {
    const register = emptyRegister();
    register.runs.push({
      id: "run123",
      recordedAt: "2026-07-14T00:00:00.000Z",
      graphHash: "abc",
      nodeCount: 4,
      edgeCount: 2,
      openRiskCount: 1,
      highestSeverity: "high",
      architectureChanged: true,
      model: "gpt-5.6-sol"
    });
    const output = renderRunHistory(register);
    expect(output).toContain("run123");
    expect(output).toContain("gpt-5.6-sol");
  });
});
